version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - ./app/frontend:/var/www/html/frontend
      - ./config/virtualhosts/peliculas.iaas.com.conf:/etc/apache2/sites-enabled/peliculas.iaas.com.conf
    ports:
      - "80:80"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    volumes:
      - ./app/backend:/var/www/html/backend
      - ./config/virtualhosts/peliculas.iaas.api.com.conf:/etc/apache2/sites-enabled/peliculas.iaas.api.com.conf
    ports:
      - "8080:80"
    links:
      - db
  db:
    image: mysql:8.0.35-debian
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=films
    volumes:
      - ./config/mysql_dump:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql #Opcional
volumes:
  mysql-data: #Opcional (si queremos mantener los datos de la base de datos)